# bible_figures_distinct.py

bible_figures = [
    # Old Testament
    "Adam",
    "Eve",
    "Cain",
    "Abel",
    "Seth",
    "Enoch",
    "Noah",
    "Shem",
    "Ham",
    "Japheth",
    "Nimrod",

    "Abraham",
    "Sarah",
    "Hagar",
    "Ishmael",
    "Isaac",
    "Rebekah",
    "Esau",
    "Jacob",
    "Rachel",
    "Leah",
    "Joseph (son of Jacob)",
    "Benjamin",

    "Potiphar",
    "Asenath",
    "Pharaoh of Exodus",

    "Moses",
    "Aaron",
    "Miriam",
    "Zipporah",
    "Jethro",
    "Joshua",
    "Caleb",
    "Balaam",
    "Rahab",

    "Deborah",
    "Barak",
    "Gideon",
    "Jephthah",
    "Samson",
    "Delilah",
    "Ruth",
    "Boaz",
    "Samuel",
    "Eli",
    "Hannah",

    "Saul",
    "Jonathan",
    "David",
    "Michal",
    "Abigail",
    "Bathsheba",
    "Nathan",
    "Joab",
    "Absalom",
    "Solomon",

    "Rehoboam",
    "Jeroboam",
    "Ahab",
    "Jezebel",
    "Hezekiah",
    "Josiah",

    "Elijah",
    "Elisha",
    "Isaiah",
    "Jeremiah",
    "Ezekiel",
    "Daniel",

    "Hosea",
    "Joel",
    "Amos",
    "Obadiah",
    "Jonah",
    "Micah",
    "Nahum",
    "Habakkuk",
    "Zephaniah",
    "Haggai",
    "Zechariah (prophet)",
    "Malachi",

    "Nebuchadnezzar",
    "Belshazzar",
    "Cyrus the Great",
    "Ezra",
    "Nehemiah",
    "Esther",
    "Mordecai",

    "Job",

    # New Testament
    "Zechariah (father of John the Baptist)",
    "Elizabeth",
    "John the Baptist",
    "Mary (mother of Jesus)",
    "Joseph (husband of Mary)",
    "Herod the Great",
    "Simeon",
    "Anna",

    "Jesus",
    "James (brother of Jesus)",
    "Jude (brother of Jesus)",

    "Peter",
    "Andrew",
    "James (son of Zebedee)",
    "John (apostle)",
    "Philip",
    "Bartholomew",
    "Thomas",
    "Matthew",
    "James (son of Alphaeus)",
    "Thaddaeus",
    "Simon the Zealot",
    "Judas Iscariot",
    "Matthias",

    "Mary Magdalene",
    "Martha",
    "Mary of Bethany",
    "Lazarus",
    "Nicodemus",
    "Joseph of Arimathea",

    "Herod Antipas",
    "Pontius Pilate",
    "Caiaphas",
    "Annas",
    "Barabbas",

    "Stephen",
    "Philip (the Evangelist)",
    "Barnabas",
    "Silas",
    "Timothy",
    "Titus",
    "Apollos",
    "Priscilla",
    "Aquila",
    "Lydia",
    "Phoebe",
    "Paul",
    "Luke",
    "Mark",

    "John of Patmos",
]